# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------

project = 'AI Guard'
copyright = '2025, Wiame El Hafid, Rjili Houssam'
author = 'Wiame El Hafid, Rjili Houssam'
release = '1.0.0'
version = '1.0.0'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings
extensions = [
    'sphinx.ext.autodoc',      # Auto-generate docs from docstrings
    'sphinx.ext.viewcode',     # Add source code links
    'sphinx.ext.napoleon',     # Support for Google/NumPy style docstrings
    'sphinx.ext.todo',         # Support for todo items
    'sphinx.ext.intersphinx',  # Link to other documentation
    'sphinx.ext.autosummary',  # Generate summary tables
    'sphinx.ext.githubpages',  # Publish to GitHub pages
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
]

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = 'en'

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets)
html_static_path = ['_static']

# Custom CSS files
html_css_files = [
    'custom.css',  # You can create this for custom styling
]

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = '_static/logo.png'  # Uncomment and add your logo

# The name of an image file (within the static path) to use as favicon
# html_favicon = '_static/favicon.ico'  # Uncomment and add your favicon

# Theme options are theme-specific and customize the look and feel of a theme
html_theme_options = {
    'canonical_url': '',
    'analytics_id': '',  # You can add Google Analytics ID here
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'style_nav_header_background': '#2980B9',  # Nice blue color
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
html_sidebars = {
    '**': [
        'globaltoc.html',
        'relations.html',
        'sourcelink.html',
        'searchbox.html'
    ]
}

# -- Extension configuration -------------------------------------------------

# -- Options for autodoc extension ------------------------------------------

# This value selects if automatically documented members are sorted
autodoc_member_order = 'bysource'

# This value is a list of autodoc directive flags that should be automatically
# applied to all autodoc directives.
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# -- Options for napoleon extension -----------------------------------------

# True to parse Google style docstrings
napoleon_google_docstring = True

# True to parse NumPy style docstrings
napoleon_numpy_docstring = True

# True to include init docstring in the class docstring
napoleon_include_init_with_doc = False

# True to include private members (like _membername) with docstrings
napoleon_include_private_with_doc = False

# True to include special members (like __membername__) with docstrings
napoleon_include_special_with_doc = True

# True to use the :param: role for each function parameter
napoleon_use_param = True

# True to use the :type: role for the type of each function parameter
napoleon_use_rtype = True

# -- Options for intersphinx extension --------------------------------------

# Mapping to external documentation
intersphinx_mapping = {
    'python': ('https://docs.python.org/3/', None),
    'flask': ('https://flask.palletsprojects.com/en/2.3.x/', None),
    'opencv': ('https://docs.opencv.org/4.x/', None),
    'numpy': ('https://numpy.org/doc/stable/', None),
    'sqlite3': ('https://docs.python.org/3/library/sqlite3.html', None),
}

# -- Options for todo extension ---------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Optio